const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Button,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Mouse,
		C3.Plugins.LocalStorage,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.Browser.Acts.LockOrientation,
		C3.Plugins.AdvancedRandom.Acts.CreateProbabilityTable,
		C3.Plugins.AdvancedRandom.Acts.SetProbabilityTable,
		C3.Plugins.AdvancedRandom.Acts.AddProbabilityEntry,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.RemoveAllDynamicLayers,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.AddLayer,
		C3.Plugins.AdvancedRandom.Exps.Weighted,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Button.Cnds.IsChecked,
		C3.Plugins.Button.Acts.SetChecked,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.LocalStorage.Cnds.OnAllGetsComplete,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows
	];
};
self.C3_JsPropNameTable = [
	{CardID: 0},
	{Weight: 0},
	{CardName: 0},
	{Grey1: 0},
	{Grey2: 0},
	{Grey3: 0},
	{Grey4: 0},
	{Grey5: 0},
	{Grey6: 0},
	{Grey7: 0},
	{Green1: 0},
	{Green2: 0},
	{Green3: 0},
	{Green4: 0},
	{Green5: 0},
	{Green6: 0},
	{Green7: 0},
	{Green8: 0},
	{Green9: 0},
	{Green10: 0},
	{Green11: 0},
	{Green12: 0},
	{Green13: 0},
	{Green14: 0},
	{Blue: 0},
	{Blue2: 0},
	{Blue3: 0},
	{Blue4: 0},
	{Blue5: 0},
	{Blue6: 0},
	{Blue7: 0},
	{Blue8: 0},
	{Blue9: 0},
	{Blue10: 0},
	{Blue11: 0},
	{Blue12: 0},
	{Blue13: 0},
	{Blue14: 0},
	{Blue15: 0},
	{Blue16: 0},
	{Blue17: 0},
	{Blue18: 0},
	{Blue19: 0},
	{Blue20: 0},
	{Red: 0},
	{Red2: 0},
	{Red3: 0},
	{Red4: 0},
	{Red5: 0},
	{Red6: 0},
	{Red7: 0},
	{Red8: 0},
	{Red9: 0},
	{Red10: 0},
	{Red11: 0},
	{Red12: 0},
	{Red13: 0},
	{Red14: 0},
	{Red15: 0},
	{Red16: 0},
	{Red17: 0},
	{Red18: 0},
	{Red19: 0},
	{Red20: 0},
	{Purple1: 0},
	{Purple2: 0},
	{Purple3: 0},
	{Purple4: 0},
	{Purple5: 0},
	{Purple6: 0},
	{Purple7: 0},
	{Purple8: 0},
	{Purple9: 0},
	{Purple10: 0},
	{Purple11: 0},
	{Purple12: 0},
	{Purple13: 0},
	{Purple14: 0},
	{Purple15: 0},
	{Purple16: 0},
	{Purple17: 0},
	{Purple18: 0},
	{Purple19: 0},
	{Purple20: 0},
	{White1: 0},
	{White2: 0},
	{White3: 0},
	{White4: 0},
	{White5: 0},
	{White6: 0},
	{White7: 0},
	{White8: 0},
	{White9: 0},
	{White10: 0},
	{White11: 0},
	{White12: 0},
	{Gold1: 0},
	{Gold2: 0},
	{Gold3: 0},
	{Gold4: 0},
	{Gold5: 0},
	{Gold6: 0},
	{Gold7: 0},
	{Gold8: 0},
	{Black1: 0},
	{Black2: 0},
	{Black3: 0},
	{Black4: 0},
	{Black5: 0},
	{SaveCard: 0},
	{SPin: 0},
	{ID: 0},
	{Slot1: 0},
	{Slot2: 0},
	{Slot3: 0},
	{Slot4: 0},
	{Slot5: 0},
	{Slot6: 0},
	{Slot7: 0},
	{ToCollection1: 0},
	{ToSPin1: 0},
	{Background: 0},
	{Background2: 0},
	{Frame: 0},
	{DeskWallpaper: 0},
	{MobileWallpaper: 0},
	{XP: 0},
	{Xbox: 0},
	{Super: 0},
	{Fallout: 0},
	{Mine: 0},
	{AdvancedRandom: 0},
	{Cards: 0},
	{Mouse: 0},
	{Empty: 0},
	{Empty2: 0},
	{Empty3: 0},
	{Empty4: 0},
	{Empty5: 0},
	{Empty6: 0},
	{Empty7: 0},
	{LocalStorage: 0},
	{PlatformInfo: 0},
	{Browser: 0},
	{Text: 0},
	{StartButton: 0},
	{Touch: 0},
	{Collect: 0},
	{BackSpin: 0},
	{Audio: 0},
	{Grey: 0},
	{Green: 0},
	{B: 0},
	{R: 0},
	{P: 0},
	{W: 0},
	{G: 0},
	{Bla: 0},
	{Family1: 0},
	{LoadingScreens: 0},
	{SavedCard: 0},
	{CurrentDrop: 0},
	{SaveSpace: 0},
	{CurrentCard: 0},
	{SavedSpace1: 0},
	{SavedSpace2: 0},
	{SavedSpace3: 0},
	{SavedSpace4: 0},
	{SavedSpace5: 0},
	{SavedSpace6: 0},
	{SavedSpace7: 0},
	{loaded: 0}
];

self.InstanceType = {
	Grey1: class extends self.ISpriteInstance {},
	Grey2: class extends self.ISpriteInstance {},
	Grey3: class extends self.ISpriteInstance {},
	Grey4: class extends self.ISpriteInstance {},
	Grey5: class extends self.ISpriteInstance {},
	Grey6: class extends self.ISpriteInstance {},
	Grey7: class extends self.ISpriteInstance {},
	Green1: class extends self.ISpriteInstance {},
	Green2: class extends self.ISpriteInstance {},
	Green3: class extends self.ISpriteInstance {},
	Green4: class extends self.ISpriteInstance {},
	Green5: class extends self.ISpriteInstance {},
	Green6: class extends self.ISpriteInstance {},
	Green7: class extends self.ISpriteInstance {},
	Green8: class extends self.ISpriteInstance {},
	Green9: class extends self.ISpriteInstance {},
	Green10: class extends self.ISpriteInstance {},
	Green11: class extends self.ISpriteInstance {},
	Green12: class extends self.ISpriteInstance {},
	Green13: class extends self.ISpriteInstance {},
	Green14: class extends self.ISpriteInstance {},
	Blue: class extends self.ISpriteInstance {},
	Blue2: class extends self.ISpriteInstance {},
	Blue3: class extends self.ISpriteInstance {},
	Blue4: class extends self.ISpriteInstance {},
	Blue5: class extends self.ISpriteInstance {},
	Blue6: class extends self.ISpriteInstance {},
	Blue7: class extends self.ISpriteInstance {},
	Blue8: class extends self.ISpriteInstance {},
	Blue9: class extends self.ISpriteInstance {},
	Blue10: class extends self.ISpriteInstance {},
	Blue11: class extends self.ISpriteInstance {},
	Blue12: class extends self.ISpriteInstance {},
	Blue13: class extends self.ISpriteInstance {},
	Blue14: class extends self.ISpriteInstance {},
	Blue15: class extends self.ISpriteInstance {},
	Blue16: class extends self.ISpriteInstance {},
	Blue17: class extends self.ISpriteInstance {},
	Blue18: class extends self.ISpriteInstance {},
	Blue19: class extends self.ISpriteInstance {},
	Blue20: class extends self.ISpriteInstance {},
	Red: class extends self.ISpriteInstance {},
	Red2: class extends self.ISpriteInstance {},
	Red3: class extends self.ISpriteInstance {},
	Red4: class extends self.ISpriteInstance {},
	Red5: class extends self.ISpriteInstance {},
	Red6: class extends self.ISpriteInstance {},
	Red7: class extends self.ISpriteInstance {},
	Red8: class extends self.ISpriteInstance {},
	Red9: class extends self.ISpriteInstance {},
	Red10: class extends self.ISpriteInstance {},
	Red11: class extends self.ISpriteInstance {},
	Red12: class extends self.ISpriteInstance {},
	Red13: class extends self.ISpriteInstance {},
	Red14: class extends self.ISpriteInstance {},
	Red15: class extends self.ISpriteInstance {},
	Red16: class extends self.ISpriteInstance {},
	Red17: class extends self.ISpriteInstance {},
	Red18: class extends self.ISpriteInstance {},
	Red19: class extends self.ISpriteInstance {},
	Red20: class extends self.ISpriteInstance {},
	Purple1: class extends self.ISpriteInstance {},
	Purple2: class extends self.ISpriteInstance {},
	Purple3: class extends self.ISpriteInstance {},
	Purple4: class extends self.ISpriteInstance {},
	Purple5: class extends self.ISpriteInstance {},
	Purple6: class extends self.ISpriteInstance {},
	Purple7: class extends self.ISpriteInstance {},
	Purple8: class extends self.ISpriteInstance {},
	Purple9: class extends self.ISpriteInstance {},
	Purple10: class extends self.ISpriteInstance {},
	Purple11: class extends self.ISpriteInstance {},
	Purple12: class extends self.ISpriteInstance {},
	Purple13: class extends self.ISpriteInstance {},
	Purple14: class extends self.ISpriteInstance {},
	Purple15: class extends self.ISpriteInstance {},
	Purple16: class extends self.ISpriteInstance {},
	Purple17: class extends self.ISpriteInstance {},
	Purple18: class extends self.ISpriteInstance {},
	Purple19: class extends self.ISpriteInstance {},
	Purple20: class extends self.ISpriteInstance {},
	White1: class extends self.ISpriteInstance {},
	White2: class extends self.ISpriteInstance {},
	White3: class extends self.ISpriteInstance {},
	White4: class extends self.ISpriteInstance {},
	White5: class extends self.ISpriteInstance {},
	White6: class extends self.ISpriteInstance {},
	White7: class extends self.ISpriteInstance {},
	White8: class extends self.ISpriteInstance {},
	White9: class extends self.ISpriteInstance {},
	White10: class extends self.ISpriteInstance {},
	White11: class extends self.ISpriteInstance {},
	White12: class extends self.ISpriteInstance {},
	Gold1: class extends self.ISpriteInstance {},
	Gold2: class extends self.ISpriteInstance {},
	Gold3: class extends self.ISpriteInstance {},
	Gold4: class extends self.ISpriteInstance {},
	Gold5: class extends self.ISpriteInstance {},
	Gold6: class extends self.ISpriteInstance {},
	Gold7: class extends self.ISpriteInstance {},
	Gold8: class extends self.ISpriteInstance {},
	Black1: class extends self.ISpriteInstance {},
	Black2: class extends self.ISpriteInstance {},
	Black3: class extends self.ISpriteInstance {},
	Black4: class extends self.ISpriteInstance {},
	Black5: class extends self.ISpriteInstance {},
	SaveCard: class extends self.IButtonInstance {},
	SPin: class extends self.IButtonInstance {},
	Slot1: class extends self.IButtonInstance {},
	Slot2: class extends self.IButtonInstance {},
	Slot3: class extends self.IButtonInstance {},
	Slot4: class extends self.IButtonInstance {},
	Slot5: class extends self.IButtonInstance {},
	Slot6: class extends self.IButtonInstance {},
	Slot7: class extends self.IButtonInstance {},
	ToCollection1: class extends self.IButtonInstance {},
	ToSPin1: class extends self.IButtonInstance {},
	Background: class extends self.IButtonInstance {},
	Background2: class extends self.IButtonInstance {},
	DeskWallpaper: class extends self.ISpriteInstance {},
	MobileWallpaper: class extends self.ISpriteInstance {},
	XP: class extends self.ISpriteInstance {},
	Xbox: class extends self.ISpriteInstance {},
	Super: class extends self.ISpriteInstance {},
	Fallout: class extends self.ISpriteInstance {},
	Mine: class extends self.ISpriteInstance {},
	AdvancedRandom: class extends self.IInstance {},
	Cards: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Empty: class extends self.ISpriteInstance {},
	Empty2: class extends self.ISpriteInstance {},
	Empty3: class extends self.ISpriteInstance {},
	Empty4: class extends self.ISpriteInstance {},
	Empty5: class extends self.ISpriteInstance {},
	Empty6: class extends self.ISpriteInstance {},
	Empty7: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	StartButton: class extends self.IButtonInstance {},
	Touch: class extends self.IInstance {},
	Collect: class extends self.IButtonInstance {},
	BackSpin: class extends self.IButtonInstance {},
	Audio: class extends self.IInstance {},
	Grey: class extends self.ISpriteInstance {},
	Green: class extends self.ISpriteInstance {},
	B: class extends self.ISpriteInstance {},
	R: class extends self.ISpriteInstance {},
	P: class extends self.ISpriteInstance {},
	W: class extends self.ISpriteInstance {},
	G: class extends self.ISpriteInstance {},
	Bla: class extends self.ISpriteInstance {},
	Family1: class extends self.IButtonInstance {},
	LoadingScreens: class extends self.ISpriteInstance {}
}